package com.rest.api.restapi.repository;

import java.util.List;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;

import com.rest.api.restapi.model.Person;

public interface UserRepository extends MongoRepository<Person, String> {
	

	// To find user in case of a random ID generated by MongoDB. As ID is the primary key &
	//If we are not able to find user's with ID generated we have to find them using username.
	
//	@Query("{'first_name' :?0}")
//	public List<Person> findByFirst_Name(String first_name);
	
//	@Query("{'first_name' :?0 , 'last_name' :?1}")
//	public List<Person> findByFirst_NameAndLast_Name(String first_name,String last_name);
	
 
}
